database:
  driver-class-name: org.sqlite.JDBC
  url: jdbc:sqlite:database/its.db
  dialect: org.hibernate.community.dialect.SQLiteDialect
  schema: database/schema.sql
  seed-data: database/seed-data.sql

jpa:
  properties:
    hibernate:
      hbm2ddl:
        auto: validate
      format_sql: true
      show_sql: false

