org.slf4j.simpleLogger.defaultLogLevel=error
org.slf4j.simpleLogger.log.org.hibernate=error
org.slf4j.simpleLogger.log.org.hibernate.orm=error
org.slf4j.simpleLogger.log.org.hibernate.engine.jdbc.connections.internal=error
org.slf4j.simpleLogger.log.org.hibernate.resource.transaction=error
org.slf4j.simpleLogger.showDateTime=false
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=false
org.slf4j.simpleLogger.showShortLogName=false
